// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omqutbfwqaumviobkddk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tcXV0YmZ3cWF1bXZpb2JrZGRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MjM1NDYsImV4cCI6MjA3MjI5OTU0Nn0.Q2cbaC05y4Ke-vIemTxK8iZjcrcTrKJlHFjkBbQwFp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});